title: XENODENNIS
description: Full Stack Developer & AI Specialist
baseurl: /xenodennis
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Collections for multilingual content
collections:
  posts_en:
    output: true
    permalink: /:year/:month/:day/:title/
  posts_zh:
    output: true
    permalink: /zh/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts_en"
    values:
      layout: post
      lang: en
  - scope:
      path: ""
      type: "posts_zh"
    values:
      layout: post
      lang: zh

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md 